basePath: /
host: localhost:8000
info:
  contact:
    email: tomazcx06@gmail.com
    name: Tomaz C. Xavier
    url: http://www.tomazcx.site
  description: CRUD of products with user authentication.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Products API
  version: "1.0"
paths:
  /users/{email}:
    get:
      consumes:
      - application/json
      description: Get user data by email
      parameters:
      - description: Account Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Show an account
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
